plugins {
    id 'fabric-loom'
    id 'maven-publish'
}

base {
    archivesName = "${rootProject.archives_base_name}-appearance"
}

apply from: rootProject.file('gradle/mod-common.gradle')

loom {
    splitEnvironmentSourceSets()
    mods {
        magicaland {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
    accessWidenerPath = file('src/main/resources/magicaland.accesswidener')
    runs {
        client { runDir 'run/client' }
        server { runDir 'run/server' }
    }
}

fabricApi {
    configureDataGeneration { client = true }
}

dependencies {
    modImplementation "software.bernie.geckolib:geckolib-fabric-1.20.1:${project.geckolib_version}"
    clientCompileOnly 'com.eliotlash.mclib:mclib:20'
    modImplementation "com.terraformersmc:modmenu:${project.modmenu_version}"
}
