plugins {
    id 'base'
    id 'fabric-loom' version '1.16-SNAPSHOT' apply false
}

allprojects {
    version = rootProject.mod_version
    group = rootProject.maven_group
}

tasks.named('build') {
    dependsOn ':appearance:build', ':gameplay:build'
}

tasks.named('assemble') {
    dependsOn ':appearance:assemble', ':gameplay:assemble'
}

tasks.named('check') {
    dependsOn ':appearance:check', ':gameplay:check'
}

tasks.named('clean') {
    dependsOn ':appearance:clean', ':gameplay:clean'
}
